let x;
const arr = [34, 55, 96, 20, 15];
//arr.push(100);
//arr.pop();
//arr.unshift(99);
//arr.reverse();
x = arr.includes(200);
x = arr.indexOf(340);
x = arr.slice(1, 4);
//x = arr.splice(1, 3);
x = arr.splice(1, 4).reverse().toString().charAt(0);
console.log(x,arr);
